<script context="module">
	import { titleSVG } from "$actions/titleSVGModule.js";

	export var text = [
		titleSVG,
		`Climate change is often spoken about in terms of total earth warming, sea-level rise, and natural disasters. But unless you are a climate scientist, a two degree rise in temperature may not be helpful in providing a tangible vision of our future. <br><br> Perhaps that’s because we’re more familiar with weather: the daily, short-term forecasts that make you pack an extra sweater or wear your rain boots. Climate, on the other hand, describes average weather systems over long periods of time.`,
		`150 years ago, a German scientist by the name of Wladimir Köppen, attempted to bridge gap between climate and weather, and used vegetation growth to classify the world into 5 distinct climate zones: <b><span class='classMap' id='aridMap' style="border-radius:2px;color:black;background-color:#ff8563">Arid</span> <span class='classMap' id='tropicalMap' style="border-radius:2px;color:white;background-color:#1761fd">Tropical</span> <span class='classMap' id='tempMap' style="border-radius:2px;color:black;background-color:#abe340">Temperate</span> <span class='classMap' id='coldMap' style="position:relative;border-radius:2px;color:white;background-color:#735fca">Cold</span> <span class='classMap' id='polarMap' style="position:relative;border-radius:2px;color:black;background-color:lightgrey">Polar</span></b>.`,
		`A quick zoom into Europe, and you can see the diversity of each of these zones. If you've ever been to Amersterdam, Barcelona, Milan, or Istanbul you know that they feel very different, yet all live within the general classification of <span class="classMap" style="border-radius:2px;font-weight:700;color:black;background-color:#abe340">Temperate</span>.`,
		`In order to distinguish the difference within these categories, there are 30 subcategories that help give more insight into the relative climates within each classification. <br><br> Here you can see these European climates broken up into: <span id='dshs' class="classMap" style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:rgb(255, 255, 0)">Temperate - Dry summer, hot summer</span>, <span id='dsws' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:#c8c800">Temperate - Dry summer, warm summer</span>, <span id='ndsws' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:rgb(100, 255, 80)">Temperate - No dry season, warm summer</span>, <span id='ndshs' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:rgb(200, 255, 80)">Temperate - No dry season, hot summer</span>.`,
		`These classifications became known as the Köppen Climate Classification and help us not only differ between weather systems of neighboring countries, but also bring insights into cities oceans apart that on average will have similar weather throughout the year. <br><br>Here we are looking at cities in <span class="classMap" style="text-shadow: 1px 1px 1px rgb(200, 255, 80), -1px -1px 1px rgb(200, 255, 80), -1px 1px 1px rgb(200, 255, 80), 1px -1px 1px rgb(200, 255, 80); position:relative;;border-radius:2px;font-weight:600;color:black;background-color:rgb(200, 255, 80)">Temperate - No dry season, hot summer</span>.`,
		`A recent study, led by climatologist Hylke Beck, used projected data from climate models along with the current Köppen Climate Classification to give a glimpse at what our world may look and feel like in 2070. <br><br>At a zoomed out level, some of these changes are hard to notice...<br><br><span  class='classMap' id='tempMap' style="border-radius:2px;font-weight:700;color:black;background-color:#abe340">Temperate</span> climates shifting north <span class="classMap" style="font-weight:700;border-radius:2px;color:white;background-color:#1761fd">Tropical</span> and <span class="classMap" style="font-weight:700;border-radius:2px;color:black;background-color:#ff8563">Arid</span> climates growing <span class="classMap" style="font-weight:700;position:relative;border-radius:2px;color:white;background-color:#735fca">Cold</span> climates dissapearing.<br><br>But what if we were to zoom into the city level to see how these climate changes, will effect the way cities feel?`,
		"This project looks at 70 global cities, and tracks their classification from 2023 to 2070. <br><br> And with climate change, your city isn't just getting hotter...it's beginning to resemble the climate of different cities.<br><br>By moving cities into the future, while leaving others in their 2023 classification, we can start to imagine what the places we love may feel like in 2070...",
		"Here we see our 70 global cities listed in their current classification. As we scroll down we can transport any city into their future classification. What sort of findings lay within the dataset?",
		"<h4>Hollywood Becomes Bollywood:</h4><br>In the year 2070, Los Angeles is predicted to increase 3 degrees celsius and moves from the Temperate to Arid classification and will feel much more like New Delhi feels today.",
		"<h4>The Scandinavian Riveria:</h4><br>In the near future, people might be bragging about their luxurious beach side resort in Copenhagen. Much of Scandavia and Northern Europe change from cold to Temperate climates.",
		"<h4>The Growth of Arid and Tropics:</h4><br>The now Temperate cities, with hot or wet summers become swallowed by the Tropical and Arid classifications. Contributing to a migration of almost 90 million people being moved from the Temperate zones into harsher environments.",
		"<h4>The Disappearance of a Classification:</h4><br>Moscow will be a lonely place in 2070, as the only remaining of our cities to exist in the Cold classification. How will the planet react as we lose our diverse climates?",
		`<h4>What stories can you discover about our future?</h4><br>Use this tool to click on any city and see their future climate zone. The cities that change zones keep the border of their previous climate home. Those with no change will show a grey border. For more information on each zone, click on the titles of the categories or sub categories <br><br><button class="explore-button" onclick="document.getElementById('step13').style.opacity = 0;document.getElementById('step13').style.zIndex = -1">Explore</button>`
	];
</script>
