<script context="module">
	import { titleSVG } from "$actions/titleSVGModule.js";

	export var text = [
		titleSVG,
		`Climate scientists say that we’re headed for more than a two degree rise in earth’s temperatures. But for most of us, that’s not really helpful in providing a tangible vision of our future. <br><br> Perhaps that’s because we’re more familiar with weather: the daily, short-term forecasts that make you pack an extra sweater or wear your rain boots. Climate, on the other hand, describes average weather systems over long periods of time.`,
		`150 years ago, German scientist Wladimir Köppen attempted to bridge gap between climate and weather, and used vegetation growth to classify the world into 5 distinct climate zones: <b><span class='classMap' id='aridMap' style="border-radius:2px;color:black;background-color:#ffc7c1">Arid</span> <span class='classMap' id='tropicalMap' style="border-radius:2px;color:black;background-color:#aff4c5">Tropical</span> <span class='classMap' id='tempMap' style="border-radius:2px;color:black;background-color:#bce3ff">Temperate</span> <span class='classMap' id='coldMap' style="position:relative;border-radius:2px;color:black;background-color:#e4ccff">Cold</span> <span class='classMap' id='polarMap' style="position:relative;border-radius:2px;color:black;background-color:white">Polar</span></b>.`,
		`A quick zoom into Europe, and you can see the diversity of each of these zones. If you’ve ever been to Amsterdam, Lisbon, Milan, or Istanbul, you know that they feel very different, yet all live within the general classification of <span class="classMap" style="border-radius:2px;font-weight:700;color:black;background-color:#bce3ff">Temperate</span>.`,
		`To distinguish the differences within these categories, the five climate zones are divided into subcategories. <br><br>For example, here you can see these European temperate climates broken up into four subcategories: <span id='dshs' class="classMap" style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:#bcf7ff">Temperate - Dry summer, hot summer</span>, <span id='dsws' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:#bfdbf0">Temperate - Dry summer, warm summer</span>, <span id='ndsws' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:black;background-color:#bcdfff">Temperate - No dry season, warm summer</span>, <span id='ndshs' class='classMap' style="position:relative;border-radius:2px;font-weight:600;color:white;background-color:#2370a8">Temperate - No dry season, hot summer</span>.`,
		`Overall, there are 30 unique subclassifications, and together they make up the Köppen Climate Classification (KCC). The KCC helps us not only differentiate between weather systems of neighboring countries, but also brings insights into cities oceans apart that on average will have similar weather throughout the year. <br><br>Here we are looking at cities in <span class="classMap" style="position:relative;;border-radius:2px;font-weight:600;color:white;background-color:#2370a8;">Temperate - No dry season, hot summer</span>.`,
		`A 2018 <a target=_self style='color: white;' 'href="https://www.nature.com/articles/sdata2018214">study</a>, led by climatologist Hylke Beck, used projected data from climate models along with the current Köppen Climate Classification to give a glimpse at what our world may look and feel like in 2070.<br><br>At a zoomed out level, some of these changes are hard to notice: <span class='classMap' id='tempMap' style="border-radius:2px;font-weight:700;color:black;background-color:#bce3ff">Temperate</span> climates shifting north <span class="classMap" style="font-weight:700;border-radius:2px;color:black;background-color:#aff4c5">Tropical</span> and <span class="classMap" style="font-weight:700;border-radius:2px;color:black;background-color:#ffc7c1">Arid</span> climates growing <span class="classMap" style="font-weight:700;position:relative;border-radius:2px;color:black;background-color:#e4ccff">Cold</span> climates disappearing.<br><br>But what if we were to zoom into the city level to see how these changes affect the way each city feels?`,
		"This project looks at 70 global cities, and tracks their classification from 2023 to 2070. <br><br> And with climate change, your city isn’t just getting hotter: it will resemble the distinctive climate of completely different places.",
		"Here we see our 70 global cities listed in their current climate classification. As we scroll down, we can transport any city into its future classification.",
		"<h4>Hollywood Becomes Bollywood:</h4><br>In 2070, Los Angeles’s temperature will increase 3 degrees celsius. The city moves from a Temperate to Arid classification and its climate will resemble how New Delhi feels today.",
		"<h4>The Scandinavian Riviera:</h4><br>In the near future, people might be bragging about their luxurious beach side resort in Copenhagen. Much of Scandinavia and Northern Europe change from Cold to Temperate climates.",
		"<h4>The Growth of Arid and Tropics:</h4><br>The now Temperate cities, with hot or wet summers, become swallowed by the Tropical and Arid classifications. Nearly 90 million people move from Temperate zones into harsher environments.",
		"<h4>The Disappearance of a Classification:</h4><br>Moscow will be a lonely place in 2070, as the only remaining of our cities to exist in the Cold classification. How will the planet react as we lose our diverse climates?",
		`<h4>What stories can you discover about our future?</h4><br>Use this tool to click on any city to reveal its future climate zone. Find out to which current city its climate will be most similar.<br><br>Within each climate subcategory, cities are ordered from highest average annual temperature top to bottom, left to right.<br><br><button class="explore-button">Explore</button>`
	];
</script>
